In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import sys
import math

In [2]:
def progress(count, total, status=''):
    bar_len = 60
    filled_len = int(round(bar_len * count / float(total)))

    percents = round(100.1 * count / float(total), 1)
    bar = '=' * filled_len + '-' * (bar_len - filled_len)

    sys.stdout.write('[%s] %s%s %s\r' % (bar, percents, '%', status))
    sys.stdout.flush()

In [3]:
meta = pd.read_csv('../data/combined.tsv', sep='\t', header=0, index_col=None)

In [4]:
meta.head()

,Virus name,Accession ID,Collection date,Location,Host,Additional location information,Gender,Patient age,Patient status,Passage,Specimen,Additional host information,Lineage,Clade
0,hCoV-19/Mayotte/IPP00846/2021,EPI_ISL_1013099,2021-01-11,Africa / Mayotte / Mamoudzou,Human,NaN,Female,61,Inpatient,Original,NaN,NaN,B.1.160,GH
1,hCoV-19/Mayotte/IPP03105/2021,EPI_ISL_1013300,2021-01-28,Africa / Mayotte / Mamoudzou,Human,NaN,Female,8,Inpatient,Original,Nasopharyngeal,NaN,B.1.351,GH
2,hCoV-19/Mayotte/IPP03108/2021,EPI_ISL_1013301,2021-01-28,Africa / Mayotte / Mamoudzou,Human,NaN,Female,49,Inpatient,Original,Nasopharyngeal,NaN,B.1.351,GH
3,hCoV-19/Mayotte/IPP03109/2021,EPI_ISL_1013302,2021-01-28,Africa / Mayotte / Mamoudzou,Human,NaN,Male,78,Inpatient,Original,Nasopharyngeal,NaN,B.1.351,GH
4,hCoV-19/Mayotte/IPP03110/2021,EPI_ISL_1013303,2021-01-28,Africa / Mayotte / Mamoudzou,Human,NaN,Male,34,Inpatient,Original,Nasopharyngeal,NaN,B.1.351,GH

In [5]:
meta['Patient status'].unique()

array(['Inpatient', 'Hospitalized', 'Live', 'Isolation',
       'Not hospitalized', 'Released', 'Recovered', 'Post mortem',
       'Outpatient', 'inpatient', 'uknown', 'Stable in quarantine',
       'Deceased', 'outpatient', 'Hospitalised', 'Patient status',
       'Discharged', 'Hospitalized (Stable)', 'Symptomatic',
       'Asymptomatic', 'Suspected Corona',
       'Suspected coronavirus infection', 'ICU', 'Overseas inflow',
       'Released, Live', 'Hospitalized (Released)',
       'Hospitalized, Asymptomatic, Alive',
       'Hospitalized, Discharged, Alive', 'Hospitalized / ICU', 'Mild',
       'Fever', 'Non-hospitalized, symptomps: sore throat',
       'Pneumonia (chest X-ray)', 'Intensive Care Unit',
       'Hospitalized (Deceased)', 'Discharged after recovery',
       'No clinical signs', 'Quarantine', 'Facility quarantine',
       'Domestic infection',
       'Initially hospitalized, but now improved and discharged',
       'Hospitalized (Mild)', 'Asymptomatic/Released', 'DAMA', 'Alive',
       'Pneumonia (chest X-ray), not critical', 'ICU; Serious', 'Stable',
       'Serious', nan, 'Non-hospitalized, symptomps: cough',
       'Quarantined', 'Critical', 'Live, mild fever and weakness',
       'Non-hospitalized, symptoms: runny nose', 'Mild Sympthoms',
       'Pneumonia', 'Undetlying DM and Ischemic Heart Disease',
       'hospitalized', 'released', 'Rebased',
       'Mild clinical signs without hospitalization',
       'Symptoms indicative of upper respiratory infection',
       'ICD-10 Disease: B34.2 Coronavirus infection, unspecified',
       'ICD-10 Disease: Z11.5 Encounter for screening for other viral diseases',
       'ICD-10 Disease: J06.9 Acute upper respiratory infection, unspecified',
       'ICD-10 Disease: U07.2 COVID-19, virus not identified',
       'ICD-10 Disease: J00-J06 Acute upper respiratory infections',
       'ICD-10 Disease: Z20.8 Contact with and exposure to other communicable diseases',
       'ICD-10 Disease: Z00.0 Encounter for general adult medical examination',
       'Paucisymptomatic', 'Symptomatic, Outpatient',
       'Contact surveillance', 'Nursing home', 'unkown', 'EHPAD',
       'Screening', 'EHPAD_IRA', 'Home', 'Mild, at home.',
       'Live, mild symptoms, at home', 'Culled for pelting',
       'ICD-10 Disease: U07.1 COVID-19, virus identified',
       'ICD-10 Disease: J06.8 Other acute upper respiratory infections of multiple sites',
       'Mild clinical signs without hospitalization. Distorted ability to smell',
       'Mild clinical signs without hospitalization. Distorted ability to smell and taste',
       'Mild symptomatology', 'Sympotomatic', 'unknonw', 'Ambulatory',
       'Hospitalized, no clinical signs', 'Mild clinical signs',
       'Mild clinical signs without hospitalization. Distorted ability to smell and taste.',
       'Mild clinical signs without hospitalization. Distorted ability to smell.',
       'Hospitalized (Intensive care unit and Released)', 'Bronchitis',
       'Hospitalized (Live)', 'Symptomatic/Reinfection', 'Mild infection',
       'Severe infection', 'Severe', 'Nursing Home',
       'Live, physical examination', 'Live, acute respiratory infection',
       'ICD-10 Disease: Z03.8 Observation for other suspected diseases and conditions',
       'Contact with and exposure to other communicable diseases',
       'Acute upper respiratory infection, unspecified',
       'Acute bronchitis', 'Pneumonia, unspecified organism',
       'Hospitalized (Moderate)', 'Hospitalized (Severe)',
       'ICD-10 Disease: Z03.8 Encounter for observation for other suspected diseases and conditions ruled out',
       'ICD-10 Disease: Z00.0 Encounter for general adult medical examination without abnormal findings',
       'ICD-10 Disease: Z04 Encounter for examination and observation for other reasons',
       'ICD-10 Disease: J18.1 Lobar pneumonia, unspecified organism',
       'ICD-10 Disease: J18.9 Pneumonia, unspecified organism',
       'ICD-10 Disease: U07.2 Virus not identified',
       'ICD-10 Disease: Z04.8 Encounter for examination and observation for request for expert evidence',
       'Hospitalized, noninvasive ventilation',
       'Mild clinical signs without hospitalization. Diarrhoea',
       'Nursing house',
       'Asymptomatic, identified as positive during preoperation investigation',
       'Hospitalized (Intensive care unit)', 'Hospitalized (Critical)',
       'ICD-10 Disease: J02.9 Acute pharyngitis, unspecified', 'Cough',
       'ICD-10 Disease: J00- Acute nasopharyngitis [common cold]',
       'ICD-10 Disease: Z10.8 Routine general health check-up of other defined subpopulations',
       'House assistance, Symptomatic', 'unknow', 'Hospitlalized', 'UCI',
       'Asymtomatic', 'Paucisymtomatic',
       'Mild symptoms (fever, cardiovascular disorders)',
       'Hospitalized, oxygenotherapy, diarrhea', 'Coronavirus infection',
       'Encounter for general adult medical examination',
       'Encounter for observation for other suspected diseases and conditions ruled out',
       'Other acute upper respiratory infections of multiple sites',
       'Aymptomatic', 'Hospidalized', 'Hospitalizes', 'Out-patient',
       'Live, asymptomatic', 'Epidemiology Study',
       'Mild clinical signs without hospitalization. Distorted ability to taste',
       'deceased', 'unkonwn', 'live', 'unknkown', 'Recovering',
       'Hospitalized (possible MIS-C)', 'symptomatic',
       'Moderate / Outpatient', 'Mild/Contact exposure/Asymptomatic',
       'Severe / ICU', 'Mild / Contact exposure / Asymptomatic', 'Screen',
       '51.0', '68.0', '42.0', '55.0', '45.0', '37.0', '103.0', '28.0',
       '58.0', '43.0', '18.0', '67.0', '71.0', '44.0', '59.0', '61.0',
       '38.0', '54.0', 'Reinfection', 'In-hospital'], dtype=object)

In [6]:
high_risk = {
    'hospitalized': meta[(meta['Patient status'].str.lower().str.contains('hospitalized|hospitalizes|hospitlalized', na=False))
                         & (~meta['Patient status'].str.lower().str.contains('non|not', na=False))],
    'inpatient': meta[meta['Patient status'].str.lower().str.contains('inpatient', na=False)],
    'deceased': meta[meta['Patient status'].str.lower().str.contains('deceased', na=False)],
    'severe': meta[meta['Patient status'].str.lower().str.contains('severe', na=False)]
}

low_risk = {
    'outpatient': meta[meta['Patient status'].str.lower().str.contains('outpatient', na=False)],
    'asymptomatic': meta[meta['Patient status'].str.lower().str.contains('asymptomatic', na=False)],
    'mild': meta[meta['Patient status'].str.lower().str.contains('mild', na=False)],
    'home': meta[meta['Patient status'].str.lower().str.contains('home|not hospitalized', na=False)]
}

In [7]:
high_risk_df = pd.concat(high_risk.values(), ignore_index=True).drop_duplicates(ignore_index=True)
low_risk_df = pd.concat(low_risk.values(), ignore_index=True).drop_duplicates(ignore_index=True)

In [8]:
high_risk_df['severe'] = 1
low_risk_df['severe'] = 0

In [9]:
final_meta_df = pd.concat([high_risk_df, low_risk_df])[['Virus name', 'Accession ID', 'Collection date', 'severe']]

In [10]:
final_meta_df['name'] = final_meta_df['Virus name'] + '|' + final_meta_df['Accession ID'] + '|' + final_meta_df['Collection date']

In [11]:
final_meta_df.head()

,Virus name,Accession ID,Collection date,severe,name
0,hCoV-19/Nigeria/Lagos01/2020,EPI_ISL_413550,2020-02-27,1,hCoV-19/Nigeria/Lagos01/2020|EPI_ISL_413550|20...
1,hCoV-19/DRC/2363/2020,EPI_ISL_437194,2020-04-14,1,hCoV-19/DRC/2363/2020|EPI_ISL_437194|2020-04-14
2,hCoV-19/Nigeria/KW298-CV48/2020,EPI_ISL_487107,2020-05-08,1,hCoV-19/Nigeria/KW298-CV48/2020|EPI_ISL_487107...
3,hCoV-19/Ghana/UHAS-K674/2020,EPI_ISL_628760,2020-07-07,1,hCoV-19/Ghana/UHAS-K674/2020|EPI_ISL_628760|20...
4,hCoV-19/Ghana/UHAS-H009/2020,EPI_ISL_628761,2020-06-16,1,hCoV-19/Ghana/UHAS-H009/2020|EPI_ISL_628761|20...

In [12]:
vcf = pd.read_csv('../data/snpeff_fixed_updated.vcf', sep='\t', skiprows=8, low_memory=False, memory_map=True)

In [13]:
vcf.shape

(15176, 26858)

In [14]:
vcf.head()

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,"NC_045512.2Severeacuterespiratorysyndromecoronavirus2isolateWuhan-Hu-1,completegenome",...,hCoV-19/Colombia/AMA-INS-VG-632/2021|EPI_ISL_956288|2021-01-13,hCoV-19/Colombia/AMA-INS-VG-633/2021|EPI_ISL_956289|2021-01-12,hCoV-19/Colombia/AMA-INS-VG-634/2021|EPI_ISL_956290|2021-01-12,hCoV-19/Colombia/AMA-INS-VG-635/2021|EPI_ISL_956291|2021-01-22,hCoV-19/Colombia/AMA-INS-VG-636/2021|EPI_ISL_956292|2021-01-22,hCoV-19/Colombia/AMA-INS-VG-637/2021|EPI_ISL_956293|2021-01-20,hCoV-19/Colombia/AMA-INS-VG-638/2021|EPI_ISL_956294|2021-01-18,hCoV-19/Colombia/AMA-INS-VG-367/2021|EPI_ISL_956297|2021-01-04,hCoV-19/Colombia/VAC-INS-RI-011/2021|EPI_ISL_956298|2021-01-13,hCoV-19/Brazil/RS-8680/2021|EPI_ISL_983865|2021-02-01
0,NC_045512.2,1,.,A,"*,C,G,T,M",.,.,ANN=C|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
1,NC_045512.2,2,.,T,"*,C,A,G,K,Y,W",.,.,ANN=A|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
2,NC_045512.2,3,.,T,"*,C,A,W,G,K",.,.,ANN=A|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
3,NC_045512.2,4,.,A,"*,G,T,W,C,M",.,.,ANN=C|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
4,NC_045512.2,5,.,A,"*,T,G,C,M",.,.,ANN=C|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1

In [15]:
ids = set(final_meta_df['Accession ID'])

In [16]:
len(ids)

8921

In [17]:
index0 = vcf.columns.str.split('|').str[0]
index1 = vcf.columns.str.split('|').str[1]

In [18]:
index0[:10]

Index(['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT',
       'NC_045512.2Severeacuterespiratorysyndromecoronavirus2isolateWuhan-Hu-1,completegenome'],
      dtype='object')

In [19]:
new_cols = list(index0[:10]) + list(index1[10:])

In [20]:
vcf.columns = new_cols

In [21]:
vcf

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,"NC_045512.2Severeacuterespiratorysyndromecoronavirus2isolateWuhan-Hu-1,completegenome",...,EPI_ISL_956288,EPI_ISL_956289,EPI_ISL_956290,EPI_ISL_956291,EPI_ISL_956292,EPI_ISL_956293,EPI_ISL_956294,EPI_ISL_956297,EPI_ISL_956298,EPI_ISL_983865
0,NC_045512.2,1,.,A,"*,C,G,T,M",.,.,ANN=C|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
1,NC_045512.2,2,.,T,"*,C,A,G,K,Y,W",.,.,ANN=A|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
2,NC_045512.2,3,.,T,"*,C,A,W,G,K",.,.,ANN=A|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
3,NC_045512.2,4,.,A,"*,G,T,W,C,M",.,.,ANN=C|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
4,NC_045512.2,5,.,A,"*,T,G,C,M",.,.,ANN=C|upstream_gene_variant|MODIFIER|ORF1ab|GU...,GT,0,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15171,NC_045512.2,29899,.,A,"*,C,T,G,H,M",.,.,ANN=C|downstream_gene_variant|MODIFIER|S|GU280...,GT,0,...,1,1,1,1,1,1,1,1,1,1
15172,NC_045512.2,29900,.,A,"*,T,G,C,M,W",.,.,ANN=C|downstream_gene_variant|MODIFIER|S|GU280...,GT,0,...,1,1,1,1,1,1,1,1,1,1
15173,NC_045512.2,29901,.,A,"*,T,G,C",.,.,ANN=C|downstream_gene_variant|MODIFIER|S|GU280...,GT,0,...,1,1,1,1,1,1,1,1,1,1
15174,NC_045512.2,29902,.,A,"*,T,C,G",.,.,ANN=C|downstream_gene_variant|MODIFIER|S|GU280...,GT,0,...,1,1,1,1,1,1,1,1,1,1
15175,NC_045512.2,29903,.,A,"*,T,C,G",.,.,ANN=C|downstream_gene_variant|MODIFIER|S|GU280...,GT,0,...,1,1,1,1,1,1,1,1,1,1

In [22]:
vcf_subset = vcf.loc[:, vcf.columns.isin(ids)]

In [23]:
vcf_subset

,EPI_ISL_455412,EPI_ISL_455413,EPI_ISL_455415,EPI_ISL_455418,EPI_ISL_455419,EPI_ISL_455422,EPI_ISL_455423,EPI_ISL_455424,EPI_ISL_455426,EPI_ISL_455427,...,EPI_ISL_942930,EPI_ISL_942931,EPI_ISL_954090,EPI_ISL_954094,EPI_ISL_954095,EPI_ISL_954096,EPI_ISL_954097,EPI_ISL_954098,EPI_ISL_954099,EPI_ISL_983865
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15171,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15172,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15173,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15174,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15175,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [24]:
severe_acc = set(final_meta_df.loc[final_meta_df['severe'] == 1]['Accession ID'])
mild_acc = set(final_meta_df.loc[final_meta_df['severe'] == 0]['Accession ID'])

In [31]:
var_id = []
severe_tot = []
mild_tot = []
frequency = []
var_type = []
var_impact = []
var_gene = []

In [32]:
for i,row in vcf_subset.iterrows():
    progress(i, len(vcf_subset))
    
    for num,var in enumerate(vcf.iloc[i]['ALT']):
        severe_num = 0
        mild_num = 0
        
        all_anns = [v.split('|')[0] for v in vcf.iloc[i]['INFO'].split(',')]
        all_anns[0] = all_anns[0].replace('ANN=', '')
          
        if var in ['A', 'T', 'C', 'G']:
            index = all_anns.index(var)
            var_id.append('{0}{1}>{2}'.format(vcf.iloc[i]['POS'], vcf.iloc[i]['REF'], var))
            var_type.append(vcf.iloc[i]['INFO'].split(',')[index].split('|')[1])
            var_impact.append(vcf.iloc[i]['INFO'].split(',')[index].split('|')[2])
            var_gene.append(vcf.iloc[i]['INFO'].split(',')[index].split('|')[3])
            
            frequency.append(len(vcf_subset.columns[(vcf_subset == num + 1).iloc[i]]) / len(vcf_subset.iloc[i]))
            
            for col in vcf_subset.columns[(vcf_subset == num + 1).iloc[i]]:
                if col in severe_acc:
                    severe_num += 1
                else:
                    mild_num += 1
                    
            severe_tot.append(severe_num)
            mild_tot.append(mild_num)
            
        else:
            continue

In [33]:
final_df = pd.DataFrame({'variant': var_id, 'num_severe': severe_tot, 'num_mild': mild_tot, 'var_type': var_type, 
                         'frequency': frequency, 'impact': var_impact, 'gene': var_gene})

In [35]:
final_df['num_freq'] = final_df['num_severe'] + final_df['num_mild']

In [38]:
final_df = final_df.loc[final_df['num_freq'] != 0]

In [39]:
final_df

,variant,num_severe,num_mild,var_type,frequency,impact,gene,num_freq
0,1A>C,2,0,upstream_gene_variant,0.000224,MODIFIER,ORF1ab,2
3,2T>C,3,1,upstream_gene_variant,0.000449,MODIFIER,ORF1ab,4
6,3T>C,3,0,upstream_gene_variant,0.000337,MODIFIER,ORF1ab,3
7,3T>A,1,1,upstream_gene_variant,0.000224,MODIFIER,ORF1ab,2
9,4A>G,8,0,upstream_gene_variant,0.000897,MODIFIER,ORF1ab,8
...,...,...,...,...,...,...,...,...
17896,29898A>T,3,1,downstream_gene_variant,0.000449,MODIFIER,S,4
17899,29899A>C,1,0,downstream_gene_variant,0.000112,MODIFIER,S,1
17902,29900A>T,3,0,downstream_gene_variant,0.000337,MODIFIER,S,3
17905,29901A>T,3,0,downstream_gene_variant,0.000337,MODIFIER,S,3
17908,29902A>T,2,0,downstream_gene_variant,0.000224,MODIFIER,S,2

In [41]:
final_df.to_csv('../data/variants.csv', index=False, header=True)

In [44]:
a = final_df.sample(10)

In [45]:
a

,variant,num_severe,num_mild,var_type,frequency,impact,gene,num_freq
9185,16733C>A,2,0,stop_gained,0.000224,HIGH,ORF1ab,2
1808,2275A>G,1,0,synonymous_variant,0.000112,LOW,ORF1ab,1
5327,8334C>T,8,0,missense_variant,0.000897,MODERATE,ORF1ab,8
9376,17122G>T,13,0,missense_variant,0.001458,MODERATE,ORF1ab,13
7485,12876C>A,2,0,missense_variant,0.000224,MODERATE,ORF1ab,2
15622,27678A>G,0,1,synonymous_variant,0.000112,LOW,ORF7a,1
12928,23611G>T,1,0,synonymous_variant,0.000112,LOW,S,1
14219,25710C>T,384,312,synonymous_variant,0.078079,LOW,ORF3a,696
912,922G>T,20,0,synonymous_variant,0.002244,LOW,ORF1ab,20
7989,14033A>G,1,0,missense_variant,0.000112,MODERATE,ORF1ab,1

In [46]:
final_df.to_csv('../data/variants_10.csv', index=False, header=True)